#!/usr/bin/env python3
"""
harness-export.py — Build a self-contained, installable `harness` plugin from the
draft source-of-truth (`_draft/harness-engineering/`).

GOAL §3.1: 하네스는 marketplace 배포 가능한 *self-contained* plugin이어야 한다.
설계 결정(사용자): 빌드 산출물은 top-level `./harness` (develop·think 등과 같은 레벨),
`_draft/harness-engineering/`는 그 source-of-truth로 유지 → 여기서 export.

왜 export가 필요한가:
  draft 레이아웃은 컨셉 문서(00~13.md, situational-rules/)를 *플러그인 밖*(draft 루트)에 둔다.
  그러나 L0 파서(`ruleslib.parse_l0`, `rules-merge.py`)는 `parent.parent/06-rules.md`(= 플러그인 루트)를 읽는다.
  설치 환경엔 draft 루트가 없으므로, export가 컨셉 문서를 플러그인 루트로 *평탄화*해 담아야
  self-contained가 된다. (이 사각은 로컬 cwd가 가려 #007 close-test SKIP처럼 놓치기 쉽다 →
  test-harness-export.sh가 hermetic tmp dest로 강제 검증.)

Usage:
  harness-export.py              # REPO_ROOT/harness 로 export
  harness-export.py --dest DIR   # 임의 위치로 export (hermetic 테스트용)
  harness-export.py --check      # export 없이 source 무결성만 점검 (exit 0/1)

멱등: dest의 *관리 대상* 산출물을 비우고 다시 채운다. dest가 export 산출물이 아니면(=.harness-export
마커도 없고 비어있지도 않으면) 거부 — 임의 디렉토리 삭제 방지.
"""
import argparse
import shutil
import sys
from pathlib import Path

# plugin/harness/scripts/harness-export.py → parents: [0]scripts [1]harness [2]plugin [3]harness-engineering [4]_draft [5]claude-skills
_HERE = Path(__file__).resolve()
DRAFT_ROOT = _HERE.parents[3]          # _draft/harness-engineering  (source-of-truth)
SRC_PLUGIN = _HERE.parents[1]          # plugin/harness
REPO_ROOT = _HERE.parents[5]           # claude-skills
DEFAULT_DEST = REPO_ROOT / "harness"

MARKER = ".harness-export"             # dest가 우리 산출물임을 표시 (멱등 안전)

# 플러그인 본체 (SRC_PLUGIN 기준 상대) — 통째 복사
PLUGIN_DIRS = ["skills", "hooks", "scripts", ".claude-plugin"]
# 컨셉 문서 (DRAFT_ROOT 기준) — 플러그인 루트로 평탄화. dev 전용(cycles/TODO/devils-advocate)은 제외.
DOC_GLOBS = ["[0-9][0-9]-*.md", "GOAL.md"]
DOC_DIRS = ["situational-rules"]

# build-time 도구는 설치 산출물에 넣지 않는다. export 안에선 경로가 깨지고(parents[5]→/home) 무의미.
EXCLUDE_NAMES = {
    "__pycache__", ".harness-export",
    "harness-export.py", "test-harness-export.sh",
    # dev/maintainer 전용 — 하네스 *자신*의 소스를 스캔(설치 플러그인엔 무의미, #011)
    "gc-scan.py", "test-gc-scan.sh",
    # NOTE(#014b): project-install.py 는 *일부러 포함*한다. 글로벌 플러그인(`harness/scripts/`)에
    # installer 가 있어야 skill Step A 가 `${CLAUDE_PLUGIN_ROOT}/scripts/project-install.py` 를
    # 해결한다. #014 에서 이를 제외했다가 프로덕션 install 이 file-not-found 로 깨졌다(F5).
    # installer 는 harness-export 에 더 이상 의존하지 않고 *평탄화 페이로드를 직접 재귀복사*하므로
    # 빌드 산출물 안에서 자급 동작한다. test-project-install.sh 는 빌드도구라 페이로드에선 뺀다.
    "test-project-install.sh",
    # export 산출물을 다시 export 해 배선 계약을 확인하는 maintainer 전용 테스트. export 안에는
    # harness-export.py 가 없으므로 포함하면 self-test 가 구조적으로 실패한다.
    "test-runtime-wiring.sh",
    # hooks/ 의 자동주입 테스트는 populated L0 를 만들려고 `../scripts/harness-export.py` 를
    # 직접 호출한다(draft 는 L0=0 이라 vacuous → 빌더로 export 컨텍스트를 만든다). export 안에는
    # harness-export.py 가 빠지므로(위 제외), 포함하면 설치 환경에서 "populated L0 불가"로 깨진다.
    # 빌드도구 의존 테스트라 페이로드에선 뺀다(test-project-install.sh 와 동형).
    "test-rule-inject.sh", "test-stage-inject.sh",
}


def _ignore(_dir, names):
    return [n for n in names if n in EXCLUDE_NAMES or n.endswith(".pyc")]


def check_source() -> list[str]:
    """Export 전 source 무결성. 누락 시 사유 리스트(빈 = OK)."""
    problems = []
    if not (SRC_PLUGIN / ".claude-plugin" / "plugin.json").exists():
        problems.append(f"plugin.json 없음: {SRC_PLUGIN/'.claude-plugin'/'plugin.json'}")
    if not (DRAFT_ROOT / "06-rules.md").exists():
        problems.append("06-rules.md 없음 (ruleslib L0 / rules-merge 런타임 의존)")
    for d in PLUGIN_DIRS:
        if not (SRC_PLUGIN / d).exists():
            problems.append(f"플러그인 디렉토리 없음: plugin/harness/{d}")
    return problems


def _safe_to_write(dest: Path) -> bool:
    if not dest.exists():
        return True
    if (dest / MARKER).exists():
        return True
    # 비어있으면 OK
    return not any(dest.iterdir())


def export(dest: Path) -> None:
    problems = check_source()
    if problems:
        print("🛑 EXPORT 거부 — source 무결성 실패:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        sys.exit(1)

    if not _safe_to_write(dest):
        print(
            f"🛑 EXPORT 거부 — dest가 비어있지 않고 export 산출물도 아님(마커 {MARKER} 없음): {dest}\n"
            f"   임의 디렉토리 삭제 방지. 의도된 export면 비우고 다시 실행.",
            file=sys.stderr,
        )
        sys.exit(1)

    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    (dest / MARKER).write_text(
        "GENERATED by harness-export.py from _draft/harness-engineering/.\n"
        "직접 편집 금지 — draft(source)를 고치고 재-export.\n",
        encoding="utf-8",
    )

    # 1) 플러그인 본체
    for d in PLUGIN_DIRS:
        shutil.copytree(SRC_PLUGIN / d, dest / d, ignore=_ignore)

    # 2) 컨셉 문서 (평탄화 → 플러그인 루트)
    copied_docs = 0
    for pat in DOC_GLOBS:
        for f in sorted(DRAFT_ROOT.glob(pat)):
            shutil.copy2(f, dest / f.name)
            copied_docs += 1
    for d in DOC_DIRS:
        src = DRAFT_ROOT / d
        if src.exists():
            shutil.copytree(src, dest / d, ignore=_ignore)

    # 3) 생성 README (CLAUDE.md update-workflow: <plugin>/README.md)
    _write_readme(dest)

    print(f"EXPORT OK → {dest}")
    print(f"  플러그인 디렉토리: {len(PLUGIN_DIRS)} · 컨셉 문서: {copied_docs} · situational-rules 포함")
    print(f"  설치 단위 self-contained: ruleslib L0 / rules-merge → {dest/'06-rules.md'} (존재: {(dest/'06-rules.md').exists()})")


def _write_readme(dest: Path) -> None:
    (dest / "README.md").write_text(
        "# harness\n\n"
        "> ⚠️ **GENERATED** — 이 디렉토리는 `_draft/harness-engineering/`에서 "
        "`harness-export.py`로 빌드된 산출물입니다. **직접 편집하지 마세요.** "
        "변경은 draft(source-of-truth)에서 하고 재-export 하세요.\n\n"
        "Harness Engineering — 솔로 dev 제품 개발 scaffolding. 사이클 진입 게이트, "
        "가설/품질-바 tamper-evident 잠금, 독립 리뷰 게이트, cross-cycle ratchet으로 "
        "*사이클별 품질 저하를 구조적으로* 막습니다.\n\n"
        "## 전제(필수): `python3`\n\n"
        "모든 hook·스크립트가 `python3` 인터프리터에 의존합니다. **PATH에 `python3`가 없으면 "
        "매 세션 SessionStart hook이 실패하고 모든 스킬 명령이 깨집니다.** `harness:install`의 "
        "Step 0가 순수 셸로 이를 먼저 확인합니다. (Windows는 `python`만 있고 `python3`가 없을 수 "
        "있으니 확인하세요.)\n\n"
        "## 설치 후 시작\n\n"
        "```\n/harness:install\n```\n\n"
        "설치 직후 `harness:install` 스킬이 대화로 L1 user-rules(`~/.harness/user-rules.md`)를 "
        "만들고, 설치 후 *언제 무엇이 로드되는지* 안내합니다. 그 다음 `harness:cycle`로 "
        "첫 사이클 진입 게이트를 실행하세요.\n\n"
        "## 핵심 스킬\n\n"
        "- `harness:install` — 첫 실행 온보딩 (L1 user-rule 대화 생성)\n"
        "- `harness:cycle` — pre-cycle 진입 게이트 + 산출물 scaffold + phase 진행"
        "(analysis→design→planning→implementation→validation; planning 대화가 여기 포함)\n"
        "- `harness:work` — 승인된 plan slice 구현 + 검증\n"
        "- `harness:review` — spec/design/plan 기준 독립 리뷰\n\n"
        "개념 문서는 `00-overview.md` ~ `13-operational-layer.md`, 규칙 레이어링은 "
        "`12-rule-layering.md`를 참고하세요.\n",
        encoding="utf-8",
    )


def main() -> None:
    ap = argparse.ArgumentParser(description="Export self-contained harness plugin from draft")
    ap.add_argument("--dest", type=Path, default=DEFAULT_DEST, help="export 대상 (기본: REPO_ROOT/harness)")
    ap.add_argument("--check", action="store_true", help="export 없이 source 무결성만 점검")
    args = ap.parse_args()

    if args.check:
        problems = check_source()
        if problems:
            print("source 무결성 실패:", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            sys.exit(1)
        print("source 무결성 OK")
        return

    export(args.dest.resolve())


if __name__ == "__main__":
    main()
